<Gerenciador>:
    Menu:
        name: 'menu'
    Tarefas:
        name:'tarefas'
    Assistente:
        name:'assistente'

<Menu>:
    BoxLayout:
        orientation:'vertical'
        padding:root.width*0.25,root.height*0.1
        spacing:'30dp' #coloca espaçamento
        canvas:
            Color:
                rgba:1,1,1,1 #padrão de cor RGB, onde "a" é transparencia, ele bloquei os canais
            Rectangle:
                size:self.size #vai ocupar tamanho do box
                pos:self.pos
                source:'imagens/menu.jpg'
        Image:
            source:'imagens/menu.jpg'
            size_hint_y: 4
            allow_stretch:True #vai permitir que o widget mudar o tamanho, OBS: isso vai distorcer
        Botao:
        Botao:
            text:"Tarefas"
            cor:0.1,0.1,0.1,1
            on_release:app.root.current = 'tarefas'
        Botao:
            text:"Assistente"
            on_release:app.root.current = 'assistente'
        Botao:
            text:"Sair"
            on_release:root.confirmacao()

<Tarefas>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious: #é o botão para voltar
                    title:"Tarefas"
                    on_release:app.root.current = 'menu'
                ActionButton: #pode deletar
                    text:"Win"
                ActionButton: #pode deletar
                    text:"Hom"
                ActionSeparator:  #cria uma barra de separação
                ActionButton:
                    text:"Sair"
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:'40sp'
            TextInput:
                id:texto
            Button:
                text:"+"
                size_hint_x:None
                width:'40sp'
                on_release:root.addWidget()

<Tarefa>:
    size_hint_y:None
    height:'100sp'
    Label:
        id:label
        font_size:'20sp'
    Button:
        text:"X"
        size_hint_x:None
        width:'40sp'
        on_release:app.root.get_screen('tarefas').removeWidget(root)

<Assistente>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious: #é o botão para voltar
                    title:"Assistente virtual"
                    on_release:app.root.current = 'menu'
                ActionButton: #pode deletar
                    text:"Win"
                ActionButton: #pode deletar
                    text:"Hom"
                ActionSeparator:  #cria uma barra de separação
                ActionButton:
                    text:"Sair"
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:'40sp'
            TextInput:
                id:texto
            Button:
                text:">"
                size_hint_x:None
                width:'40sp'
                on_release:root.mensagem(texto.text)