<Tarefas>: #O "Scrollview so pode ter um wudget filho"
    orientation:'vertical'
    ScrollView:
        BoxLayout:
            id:box
            orientation:'vertical'
            size_hint_y:None
            height:self.minimum_height
    BoxLayout:
        size_hint_y:None #Colou "None" pois preciza tornar editavel o "height" a baixo
        height:60
        TextInput:
            id:texto
        Button:
            text:"+"
            size_hint_x:None #Colou "None" pois preciza tornar editavel o "width" a baixo
            width:60
            on_release:root.addWidget()
<Tarefa>:
    size_hint_y:None
    height:200
    Label:
        id: label
        font_size:30
    Button:
        text:'x'
        size_hint_x:None
        width:60
        on_release:app.root.ids.box.remove_widget(root) #significa o  widget maior que no caso é <Tarefa>, remove_widget(root) poderia ser usado self.parents que referencia o pai do button