<Gerenciador>:
    Menu:
        name: 'menu'
    Tarefas:
        name:'tarefas'

<Menu>:
    BoxLayout:
        orientation:'vertical'
        padding:200
        spacing:10 #coloca espaçamento
        canvas:
            Color:
                rgba:1,1,1,1 #padrão de cor RGB, onde "a" é transparencia, ele bloquei os canais
            Rectangle:
                size:self.size #vai ocupar tamanho do box
                pos:self.pos
                source:'imagens/menu.jpg'
        Image:
            source:'imagens/menu.jpg'
            size_hint_y: None
            height:300
            allow_stretch:True #vai permitir que o widget mudar o tamanho, OBS: isso vai distorcer
        Botao:
            size_hint_y: None
            height:50
        Button:
            text:"Tarefas"
            size_hint_y: None
            height:50
            on_release:app.root.current = 'tarefas'
        Botao:
            text:"Assistente"
            size_hint_y: None
            height:50
        Botao:
            text:"Sair"
            size_hint_y: None
            height:50
            on_release:app.stop() #comande para incerra aplicativo

<Botao@ButtonBehavior+Label>: #erras os eventos do bottun
    canvas.before:
        Color:
            rgba:0.1,0.5,0.7,1
        Ellipse:
            pos:self.pos
            size:self.height,self.height
        Ellipse:
            pos:self.x+self.width-self.height,self.y
            size:self.height,self.height
        Rectangle:
            pos:self.x+self.height/2.0,self.y
            size:self.width-self.height,self.height

<Tarefas>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious: #é o botão para voltar
                    title:"Tarefas"
                    on_release:app.root.current = 'menu'
                ActionButton: #pode deletar
                    text:"Win"
                ActionButton: #pode deletar
                    text:"Hom"
                ActionSeparator:  #cria uma barra de separação
                ActionButton:
                    text:"Sair"
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:60
            TextInput:
                id:texto
            Button:
                text:"+"
                size_hint_x:None
                width:60
                on_release:root.addWidget()

<Tarefa>:
    size_hint_y:None
    height:200
    Label:
        id:label
        font_size:30
    Button:
        text:"X"
        size_hint_x:None
        width:60
        on_release:app.root.get_screen('tarefas').ids.box.remove_widget(root)