<Gerenciador>:
    Menu:
        name: 'menu'
    Tarefas:
        name:'tarefas'

<Menu>:
    BoxLayout:
        orientation:'vertical'
        padding:200
        spacing:50 #coloca espaçamento
        Image:
            source:'imagens/menu.jpg'
            size_hint_y: None
            height:300
            allow_stretch:True #vai permitir que o widget mudar o tamanho, OBS: isso vai distorcer
        Button:
            text:"Tarefas"
            size_hint_y: None
            height:30
            on_release:app.root.current = 'tarefas'
        Button:
            text:"Assistente"
            size_hint_y: None
            height:30
        Button:
            text:"Sair"
            size_hint_y: None
            height:30
            on_release:app.stop() #comande para incerra aplicativo

<Tarefas>:
    BoxLayout:
        orientation:'vertical'
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:60
            TextInput:
                id:texto
            Button:
                text:"+"
                size_hint_x:None
                width:60
                on_release:root.addWidget()

<Tarefa>:
    size_hint_y:None
    height:200
    Label:
        id:label
        font_size:30
    Button:
        text:"X"
        size_hint_x:None
        width:60
        on_release:app.root.get_screen('tarefas').ids.box.remove_widget(root)