#:kivy 1.1

<Home>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: 0, 1, 0, 1
            Rectangle:
                # self here refers to the widget i.e FloatLayout
                pos: root.pos
                size: root.size
        Button:
            text: 'Hello World!!'
            size_hint: root.size_hint_x / 0.5, root.size_hint_y / 0.5
            pos_hint: {'center_x':.5, 'center_y': .5}
